export const EPG_URL = process.env.EPG_URL;
export const PROXY_SERVER_URL = process.env.PROXY_SERVER_URL;
export const DEFAULT_STREAM_URL = process.env.DEFAULT_STREAM_URL;
export const DRM_LICENSE_SERVER = process.env.DRM_LICENSE_SERVER;
export const ANGEL_ONE_STREAM_URL = process.env.ANGEL_ONE_STREAM_URL;
export const TEARS_OF_STEEL_STREAM_URL = process.env.TEARS_OF_STEEL_STREAM_URL;
export const BIG_BUCK_BUNNY_STREAM_URL = process.env.BIG_BUCK_BUNNY_STREAM_URL;

export const STREAMS = [
	ANGEL_ONE_STREAM_URL,
	TEARS_OF_STEEL_STREAM_URL,
	BIG_BUCK_BUNNY_STREAM_URL
];
